### ISSUE TITLE
Is this still supported?  Pyupdater is no longer being maintained

### ISSUE THREAD

**Issue by Hardcorekila** [dennisvang/tufup#49]
Please file issues only for bugs or feature requests.
If you have a question, please post it on https://stackoverflow.com with the 'tufup' tag.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version [e.g. 10]:
 - Python version [e.g.3.10.6]:

**Additional context**
For example list your project dependencies, if relevant.

**Comment by dennisvang** [comment]
@Hardcorekila Yes, `tufup` is still supported.

In fact, `tufup` was created *because* PyUpdater is no longer maintained.

`tufup` provides the same basic functionality as PyUpdater, but with better (potential) security through the use of [TUF][1].

The readme provides [instructions for migrating from PyUpdater to tufup][2].

[1]: https://theupdateframework.io/
[2]: https://github.com/dennisvang/tufup/blob/master/README.md#migrating-from-other-update-frameworks

**Comment by dennisvang** [comment]
Do note that, although `tufup` offers the same basic functionality as PyUpdater, there are some differences:

- `tufup` uses `python-tuf` to secure the update process. This means you'll need to understand a little bit about the principles behind [TUF][1]. You can tailor the level of security to your needs, from highly secure, to slightly secure.
- PyUpdater was tightly integrated with [PyInstaller][2], but `tufup` is not. You *can* use `tufup` with PyInstaller, as illustrated in the [tufup-example][3], but it is not required. You can also use it with any other packaging method, or you can even distribute a plain python script, or just any directory of files.
- PyUpdater's release handling of channels was [broken][4], `tufup` handles them just fine.

[1]: https://theupdateframework.io/overview/
[2]: https://pyinstaller.org/en/stable/
[3]: https://github.com/dennisvang/tufup-example
[4]: https://github.com/Digital-Sapphire/PyUpdater/issues/255

**Comment by Hardcorekila** [comment]
@dennisvang  I seem to be getting errors from the example would my best bet be to just use pyupdater which I am familiar with and migrate from that?

```
C:\Users\vinni\PycharmProjects\pythonProject3\venv\Scripts\python.exe C:\Users\vinni\PycharmProjects\pythonProject3\pyupdater.py 
Traceback (most recent call last):
  File "C:\Users\vinni\PycharmProjects\pythonProject3\pyupdater.py", line 8, in <module>
    from tufup.repo import (
  File "C:\Users\vinni\AppData\Local\Programs\Python\Python310\lib\site-packages\tufup\__init__.py", line 4, in <module>
    from tufup.repo import cli
  File "C:\Users\vinni\AppData\Local\Programs\Python\Python310\lib\site-packages\tufup\repo\__init__.py", line 9, in <module>
    import setuptools.config.expand  # noqa
ModuleNotFoundError: No module named 'setuptools.config.expand'; 'setuptools.config' is not a package

Process finished with exit code 1
```

**Comment by dennisvang** [comment]
@Hardcorekila No you should be able to run the example. This error is caused by an old version of setuptools.

It looks like you haven't installed all the dev requirements from the `tufup-example` repo:

`pip install -r requirements-dev.txt`

**Comment by Hardcorekila** [comment]
@dennisvang After using pip install -r requirements.txt -r requirements-dev.txt --upgrade as example:

```
C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master>repo_init.py
Traceback (most recent call last):
  File "C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master\repo_init.py", line 5, in <module>
    from myapp.settings import APP_NAME
ModuleNotFoundError: No module named 'myapp'

C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master>create_pyinstaller_bundle.bat

C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master>pyinstaller.exe main.spec --clean -y --distpath temp/dist --workpath temp/build
251 INFO: PyInstaller: 5.4.1
251 INFO: Python: 3.10.7
259 INFO: Platform: Windows-10-10.0.22621-SP0
261 INFO: UPX is not available.
261 INFO: Removing temporary files and cleaning cache in C:\Users\vinni\AppData\Local\pyinstaller
264 INFO: Extending PYTHONPATH with paths
['C:\\Users\\vinni\\PycharmProjects\\pythonProject3\\pyinstaller '
 'projects\\OTHER\\cpdemo-master\\setup\\tufup-example-master\\src']
725 INFO: checking Analysis
726 INFO: Building Analysis because Analysis-00.toc is non existent
726 INFO: Initializing module dependency graph...
728 INFO: Caching module graph hooks...
735 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
738 INFO: Analyzing base_library.zip ...
2172 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
3012 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
4187 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
4585 INFO: Caching module dependency graph...
4678 INFO: running Analysis Analysis-00.toc
4691 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\vinni\AppData\Local\Programs\Python\Python310\python.exe
4807 INFO: Analyzing C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master\src\main.py
4977 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
6627 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
7001 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
7054 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
7073 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
7323 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
8558 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
8631 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
8947 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
9355 INFO: Loading module hook 'hook-jinja2.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
9855 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
10694 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
10841 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12556 INFO: Loading module hook 'hook-nacl.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
13122 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
14396 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
14544 INFO: Processing module hooks...
14611 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
14693 INFO: Loading module hook 'hook-win32com.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
14695 INFO: Loading module hook 'hook-pythoncom.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
15006 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
15315 INFO: Processing pre-find module path hook site from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
15317 INFO: site: retargeting to fake-dir 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\fake-modules'
15891 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
17226 INFO: Looking for ctypes DLLs
17236 INFO: Analyzing run-time hooks ...
17242 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
17243 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
17243 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
17248 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
17250 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
17252 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
17256 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pywintypes.py'
17257 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_pythoncom.py'
17257 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
17258 INFO: Including run-time hook 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
17272 INFO: Looking for dynamic libraries
493 INFO: Extra DLL search directories (AddDllDirectory): []
493 INFO: Extra DLL search directories (PATH): ['C:\\Program Files\\Microsoft\\jdk-11.0.12.7-hotspot\\bin', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files (x86)\\platform-tools', 'C:\\Program Files\\Mullvad VPN\\resources', 'C:\\Android', 'C:\\Zulu-OpenJDK-11\\zulu17.36.15-ca-jdk17.0.4-win_i686\\bin\\bin', 'C:\\Zulu-OpenJDK-11\\zulu17.36.15-ca-jdk17.0.4-win_i686\\bin', 'C:\\Program Files (x86)\\Boxcryptor\\bin\\', 'C:\\Program Files\\Calibre2\\', 'C:\\Program Files\\7-Zip', 'C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\', 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat', 'C:\\Users\\vinni\\AppData\\Local\\Programs\\Python\\Python310\\', 'C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22621.0\\arm64', 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\ProgramData\\chocolatey\\bin', 'C:\\Program Files (x86)\\Gpg4win\\..\\GnuPG\\bin', '"C:\\Users\\vinni\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Program Files (x86)\\platform-tools"', 'C:\\Program Files\\JetBrains\\PyCharm 2022.2.1\\bin', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.2\\bin', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.2.1\\bin', 'C:\\Users\\vinni\\.dotnet\\tools', 'C:\\Users\\vinni\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Program Files\\GPAC', 'C:\\Users\\vinni\\AppData\\Roaming\\cabal\\bin', 'C:\\tools\\ghc-9.4.2\\bin', 'C:\\tools\\msys64', 'C:\\Users\\vinni\\AppData\\Local\\GitHubDesktop\\bin']
18320 INFO: Looking for eggs
18320 INFO: Using Python library C:\Users\vinni\AppData\Local\Programs\Python\Python310\python310.dll
18321 INFO: Found binding redirects:
[]
18326 INFO: Warnings written to C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master\temp\build\main\warn-main.txt
18403 INFO: Graph cross-reference written to C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master\temp\build\main\xref-main.html
18420 INFO: Appending 'datas' from .spec
Unable to find "C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master\temp\repository\metadata\root.json" when adding binary and data files.

C:\Users\vinni\PycharmProjects\pythonProject3\pyinstaller projects\OTHER\cpdemo-master\setup\tufup-example-master>
```

**Comment by Hardcorekila** [comment]
@dennisvang  Any chance of a video tutorial with an example that incorporates say Bitbucket or Github in the future?  I.e Updating 1.0 -> 1.1 and then 1.1 to 1.2

**Comment by dennisvang** [comment]
@Hardcorekila Unfortunately, setting up workflows for Bitbucket or Github, like configuring servers, is outside the scope of `tufup`. It's just too specific to your implementation, and there are too many different ways to do it.

The tufup-example repo illustrates how the basic components of the update system interact. How to implement this in production is up to the user.

**Comment by dennisvang** [comment]
@Hardcorekila Just curious: Did you get the example up and running?
